// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_CHATLOCATED
#define LQTG_TYPE_CHATLOCATED

#include "telegramtypeobject.h"

#include <QMetaType>
#include <QVariant>
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

#include <QtGlobal>

class LIBQTELEGRAMSHARED_EXPORT ChatLocated : public TelegramTypeObject
{
public:
    enum ChatLocatedClassType {
        typeChatLocated = 0x3631cf4c
    };

    ChatLocated(ChatLocatedClassType classType = typeChatLocated, InboundPkt *in = 0);
    ChatLocated(InboundPkt *in);
    ChatLocated(const Null&);
    virtual ~ChatLocated();

    void setChatId(qint32 chatId);
    qint32 chatId() const;

    void setDistance(qint32 distance);
    qint32 distance() const;

    void setClassType(ChatLocatedClassType classType);
    ChatLocatedClassType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    QMap<QString, QVariant> toMap() const;
    static ChatLocated fromMap(const QMap<QString, QVariant> &map);

    bool operator ==(const ChatLocated &b) const;

    bool operator==(bool stt) const { return isNull() != stt; }
    bool operator!=(bool stt) const { return !operator ==(stt); }

    QByteArray getHash(QCryptographicHash::Algorithm alg = QCryptographicHash::Md5) const;

private:
    qint32 m_chatId;
    qint32 m_distance;
    ChatLocatedClassType m_classType;
};

Q_DECLARE_METATYPE(ChatLocated)

QDataStream LIBQTELEGRAMSHARED_EXPORT &operator<<(QDataStream &stream, const ChatLocated &item);
QDataStream LIBQTELEGRAMSHARED_EXPORT &operator>>(QDataStream &stream, ChatLocated &item);

inline ChatLocated::ChatLocated(ChatLocatedClassType classType, InboundPkt *in) :
    m_chatId(0),
    m_distance(0),
    m_classType(classType)
{
    if(in) fetch(in);
}

inline ChatLocated::ChatLocated(InboundPkt *in) :
    m_chatId(0),
    m_distance(0),
    m_classType(typeChatLocated)
{
    fetch(in);
}

inline ChatLocated::ChatLocated(const Null &null) :
    TelegramTypeObject(null),
    m_chatId(0),
    m_distance(0),
    m_classType(typeChatLocated)
{
}

inline ChatLocated::~ChatLocated() {
}

inline void ChatLocated::setChatId(qint32 chatId) {
    m_chatId = chatId;
}

inline qint32 ChatLocated::chatId() const {
    return m_chatId;
}

inline void ChatLocated::setDistance(qint32 distance) {
    m_distance = distance;
}

inline qint32 ChatLocated::distance() const {
    return m_distance;
}

inline bool ChatLocated::operator ==(const ChatLocated &b) const {
    return m_classType == b.m_classType &&
           m_chatId == b.m_chatId &&
           m_distance == b.m_distance;
}

inline void ChatLocated::setClassType(ChatLocated::ChatLocatedClassType classType) {
    m_classType = classType;
}

inline ChatLocated::ChatLocatedClassType ChatLocated::classType() const {
    return m_classType;
}

inline bool ChatLocated::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeChatLocated: {
        m_chatId = in->fetchInt();
        m_distance = in->fetchInt();
        m_classType = static_cast<ChatLocatedClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

inline bool ChatLocated::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeChatLocated: {
        out->appendInt(m_chatId);
        out->appendInt(m_distance);
        return true;
    }
        break;
    
    default:
        return false;
    }
}

inline QMap<QString, QVariant> ChatLocated::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeChatLocated: {
        result["classType"] = "ChatLocated::typeChatLocated";
        result["chatId"] = QVariant::fromValue<qint32>(chatId());
        result["distance"] = QVariant::fromValue<qint32>(distance());
        return result;
    }
        break;
    
    default:
        return result;
    }
}

inline ChatLocated ChatLocated::fromMap(const QMap<QString, QVariant> &map) {
    ChatLocated result;
    if(map.value("classType").toString() == "ChatLocated::typeChatLocated") {
        result.setClassType(typeChatLocated);
        result.setChatId( map.value("chatId").value<qint32>() );
        result.setDistance( map.value("distance").value<qint32>() );
        return result;
    }
    return result;
}

inline QByteArray ChatLocated::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

inline QDataStream &operator<<(QDataStream &stream, const ChatLocated &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case ChatLocated::typeChatLocated:
        stream << item.chatId();
        stream << item.distance();
        break;
    }
    return stream;
}

inline QDataStream &operator>>(QDataStream &stream, ChatLocated &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<ChatLocated::ChatLocatedClassType>(type));
    switch(type) {
    case ChatLocated::typeChatLocated: {
        qint32 m_chat_id;
        stream >> m_chat_id;
        item.setChatId(m_chat_id);
        qint32 m_distance;
        stream >> m_distance;
        item.setDistance(m_distance);
    }
        break;
    }
    return stream;
}


#endif // LQTG_TYPE_CHATLOCATED
