// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_DOCUMENTATTRIBUTE
#define LQTG_TYPE_DOCUMENTATTRIBUTE

#include "telegramtypeobject.h"

#include <QMetaType>
#include <QVariant>
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

#include <QString>
#include <QtGlobal>
#include "inputstickerset.h"

class LIBQTELEGRAMSHARED_EXPORT DocumentAttribute : public TelegramTypeObject
{
public:
    enum DocumentAttributeClassType {
        typeDocumentAttributeImageSize = 0x6c37c15c,
        typeDocumentAttributeAnimated = 0x11b58939,
        typeDocumentAttributeSticker = 0x3a556302,
        typeDocumentAttributeVideo = 0x5910cccb,
        typeDocumentAttributeAudio = 0x51448e5,
        typeDocumentAttributeFilename = 0x15590068
    };

    DocumentAttribute(DocumentAttributeClassType classType = typeDocumentAttributeImageSize, InboundPkt *in = 0);
    DocumentAttribute(InboundPkt *in);
    DocumentAttribute(const Null&);
    virtual ~DocumentAttribute();

    void setAlt(const QString &alt);
    QString alt() const;

    void setDuration(qint32 duration);
    qint32 duration() const;

    void setFileName(const QString &fileName);
    QString fileName() const;

    void setH(qint32 h);
    qint32 h() const;

    void setStickerset(const InputStickerSet &stickerset);
    InputStickerSet stickerset() const;

    void setW(qint32 w);
    qint32 w() const;

    void setClassType(DocumentAttributeClassType classType);
    DocumentAttributeClassType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    QMap<QString, QVariant> toMap() const;
    static DocumentAttribute fromMap(const QMap<QString, QVariant> &map);

    bool operator ==(const DocumentAttribute &b) const;

    bool operator==(bool stt) const { return isNull() != stt; }
    bool operator!=(bool stt) const { return !operator ==(stt); }

    QByteArray getHash(QCryptographicHash::Algorithm alg = QCryptographicHash::Md5) const;

private:
    QString m_alt;
    qint32 m_duration;
    QString m_fileName;
    qint32 m_h;
    InputStickerSet m_stickerset;
    qint32 m_w;
    DocumentAttributeClassType m_classType;
};

Q_DECLARE_METATYPE(DocumentAttribute)

QDataStream LIBQTELEGRAMSHARED_EXPORT &operator<<(QDataStream &stream, const DocumentAttribute &item);
QDataStream LIBQTELEGRAMSHARED_EXPORT &operator>>(QDataStream &stream, DocumentAttribute &item);

inline DocumentAttribute::DocumentAttribute(DocumentAttributeClassType classType, InboundPkt *in) :
    m_duration(0),
    m_h(0),
    m_w(0),
    m_classType(classType)
{
    if(in) fetch(in);
}

inline DocumentAttribute::DocumentAttribute(InboundPkt *in) :
    m_duration(0),
    m_h(0),
    m_w(0),
    m_classType(typeDocumentAttributeImageSize)
{
    fetch(in);
}

inline DocumentAttribute::DocumentAttribute(const Null &null) :
    TelegramTypeObject(null),
    m_duration(0),
    m_h(0),
    m_w(0),
    m_classType(typeDocumentAttributeImageSize)
{
}

inline DocumentAttribute::~DocumentAttribute() {
}

inline void DocumentAttribute::setAlt(const QString &alt) {
    m_alt = alt;
}

inline QString DocumentAttribute::alt() const {
    return m_alt;
}

inline void DocumentAttribute::setDuration(qint32 duration) {
    m_duration = duration;
}

inline qint32 DocumentAttribute::duration() const {
    return m_duration;
}

inline void DocumentAttribute::setFileName(const QString &fileName) {
    m_fileName = fileName;
}

inline QString DocumentAttribute::fileName() const {
    return m_fileName;
}

inline void DocumentAttribute::setH(qint32 h) {
    m_h = h;
}

inline qint32 DocumentAttribute::h() const {
    return m_h;
}

inline void DocumentAttribute::setStickerset(const InputStickerSet &stickerset) {
    m_stickerset = stickerset;
}

inline InputStickerSet DocumentAttribute::stickerset() const {
    return m_stickerset;
}

inline void DocumentAttribute::setW(qint32 w) {
    m_w = w;
}

inline qint32 DocumentAttribute::w() const {
    return m_w;
}

inline bool DocumentAttribute::operator ==(const DocumentAttribute &b) const {
    return m_classType == b.m_classType &&
           m_alt == b.m_alt &&
           m_duration == b.m_duration &&
           m_fileName == b.m_fileName &&
           m_h == b.m_h &&
           m_stickerset == b.m_stickerset &&
           m_w == b.m_w;
}

inline void DocumentAttribute::setClassType(DocumentAttribute::DocumentAttributeClassType classType) {
    m_classType = classType;
}

inline DocumentAttribute::DocumentAttributeClassType DocumentAttribute::classType() const {
    return m_classType;
}

inline bool DocumentAttribute::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeDocumentAttributeImageSize: {
        m_w = in->fetchInt();
        m_h = in->fetchInt();
        m_classType = static_cast<DocumentAttributeClassType>(x);
        return true;
    }
        break;
    
    case typeDocumentAttributeAnimated: {
        m_classType = static_cast<DocumentAttributeClassType>(x);
        return true;
    }
        break;
    
    case typeDocumentAttributeSticker: {
        m_alt = in->fetchQString();
        m_stickerset.fetch(in);
        m_classType = static_cast<DocumentAttributeClassType>(x);
        return true;
    }
        break;
    
    case typeDocumentAttributeVideo: {
        m_duration = in->fetchInt();
        m_w = in->fetchInt();
        m_h = in->fetchInt();
        m_classType = static_cast<DocumentAttributeClassType>(x);
        return true;
    }
        break;
    
    case typeDocumentAttributeAudio: {
        m_duration = in->fetchInt();
        m_classType = static_cast<DocumentAttributeClassType>(x);
        return true;
    }
        break;
    
    case typeDocumentAttributeFilename: {
        m_fileName = in->fetchQString();
        m_classType = static_cast<DocumentAttributeClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

inline bool DocumentAttribute::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeDocumentAttributeImageSize: {
        out->appendInt(m_w);
        out->appendInt(m_h);
        return true;
    }
        break;
    
    case typeDocumentAttributeAnimated: {
        return true;
    }
        break;
    
    case typeDocumentAttributeSticker: {
        out->appendQString(m_alt);
        m_stickerset.push(out);
        return true;
    }
        break;
    
    case typeDocumentAttributeVideo: {
        out->appendInt(m_duration);
        out->appendInt(m_w);
        out->appendInt(m_h);
        return true;
    }
        break;
    
    case typeDocumentAttributeAudio: {
        out->appendInt(m_duration);
        return true;
    }
        break;
    
    case typeDocumentAttributeFilename: {
        out->appendQString(m_fileName);
        return true;
    }
        break;
    
    default:
        return false;
    }
}

inline QMap<QString, QVariant> DocumentAttribute::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeDocumentAttributeImageSize: {
        result["classType"] = "DocumentAttribute::typeDocumentAttributeImageSize";
        result["w"] = QVariant::fromValue<qint32>(w());
        result["h"] = QVariant::fromValue<qint32>(h());
        return result;
    }
        break;
    
    case typeDocumentAttributeAnimated: {
        result["classType"] = "DocumentAttribute::typeDocumentAttributeAnimated";
        return result;
    }
        break;
    
    case typeDocumentAttributeSticker: {
        result["classType"] = "DocumentAttribute::typeDocumentAttributeSticker";
        result["alt"] = QVariant::fromValue<QString>(alt());
        result["stickerset"] = m_stickerset.toMap();
        return result;
    }
        break;
    
    case typeDocumentAttributeVideo: {
        result["classType"] = "DocumentAttribute::typeDocumentAttributeVideo";
        result["duration"] = QVariant::fromValue<qint32>(duration());
        result["w"] = QVariant::fromValue<qint32>(w());
        result["h"] = QVariant::fromValue<qint32>(h());
        return result;
    }
        break;
    
    case typeDocumentAttributeAudio: {
        result["classType"] = "DocumentAttribute::typeDocumentAttributeAudio";
        result["duration"] = QVariant::fromValue<qint32>(duration());
        return result;
    }
        break;
    
    case typeDocumentAttributeFilename: {
        result["classType"] = "DocumentAttribute::typeDocumentAttributeFilename";
        result["fileName"] = QVariant::fromValue<QString>(fileName());
        return result;
    }
        break;
    
    default:
        return result;
    }
}

inline DocumentAttribute DocumentAttribute::fromMap(const QMap<QString, QVariant> &map) {
    DocumentAttribute result;
    if(map.value("classType").toString() == "DocumentAttribute::typeDocumentAttributeImageSize") {
        result.setClassType(typeDocumentAttributeImageSize);
        result.setW( map.value("w").value<qint32>() );
        result.setH( map.value("h").value<qint32>() );
        return result;
    }
    if(map.value("classType").toString() == "DocumentAttribute::typeDocumentAttributeAnimated") {
        result.setClassType(typeDocumentAttributeAnimated);
        return result;
    }
    if(map.value("classType").toString() == "DocumentAttribute::typeDocumentAttributeSticker") {
        result.setClassType(typeDocumentAttributeSticker);
        result.setAlt( map.value("alt").value<QString>() );
        result.setStickerset( InputStickerSet::fromMap(map.value("stickerset").toMap()) );
        return result;
    }
    if(map.value("classType").toString() == "DocumentAttribute::typeDocumentAttributeVideo") {
        result.setClassType(typeDocumentAttributeVideo);
        result.setDuration( map.value("duration").value<qint32>() );
        result.setW( map.value("w").value<qint32>() );
        result.setH( map.value("h").value<qint32>() );
        return result;
    }
    if(map.value("classType").toString() == "DocumentAttribute::typeDocumentAttributeAudio") {
        result.setClassType(typeDocumentAttributeAudio);
        result.setDuration( map.value("duration").value<qint32>() );
        return result;
    }
    if(map.value("classType").toString() == "DocumentAttribute::typeDocumentAttributeFilename") {
        result.setClassType(typeDocumentAttributeFilename);
        result.setFileName( map.value("fileName").value<QString>() );
        return result;
    }
    return result;
}

inline QByteArray DocumentAttribute::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

inline QDataStream &operator<<(QDataStream &stream, const DocumentAttribute &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case DocumentAttribute::typeDocumentAttributeImageSize:
        stream << item.w();
        stream << item.h();
        break;
    case DocumentAttribute::typeDocumentAttributeAnimated:
        
        break;
    case DocumentAttribute::typeDocumentAttributeSticker:
        stream << item.alt();
        stream << item.stickerset();
        break;
    case DocumentAttribute::typeDocumentAttributeVideo:
        stream << item.duration();
        stream << item.w();
        stream << item.h();
        break;
    case DocumentAttribute::typeDocumentAttributeAudio:
        stream << item.duration();
        break;
    case DocumentAttribute::typeDocumentAttributeFilename:
        stream << item.fileName();
        break;
    }
    return stream;
}

inline QDataStream &operator>>(QDataStream &stream, DocumentAttribute &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<DocumentAttribute::DocumentAttributeClassType>(type));
    switch(type) {
    case DocumentAttribute::typeDocumentAttributeImageSize: {
        qint32 m_w;
        stream >> m_w;
        item.setW(m_w);
        qint32 m_h;
        stream >> m_h;
        item.setH(m_h);
    }
        break;
    case DocumentAttribute::typeDocumentAttributeAnimated: {
        
    }
        break;
    case DocumentAttribute::typeDocumentAttributeSticker: {
        QString m_alt;
        stream >> m_alt;
        item.setAlt(m_alt);
        InputStickerSet m_stickerset;
        stream >> m_stickerset;
        item.setStickerset(m_stickerset);
    }
        break;
    case DocumentAttribute::typeDocumentAttributeVideo: {
        qint32 m_duration;
        stream >> m_duration;
        item.setDuration(m_duration);
        qint32 m_w;
        stream >> m_w;
        item.setW(m_w);
        qint32 m_h;
        stream >> m_h;
        item.setH(m_h);
    }
        break;
    case DocumentAttribute::typeDocumentAttributeAudio: {
        qint32 m_duration;
        stream >> m_duration;
        item.setDuration(m_duration);
    }
        break;
    case DocumentAttribute::typeDocumentAttributeFilename: {
        QString m_file_name;
        stream >> m_file_name;
        item.setFileName(m_file_name);
    }
        break;
    }
    return stream;
}


#endif // LQTG_TYPE_DOCUMENTATTRIBUTE
