// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_GEOCHATSLOCATED
#define LQTG_TYPE_GEOCHATSLOCATED

#include "telegramtypeobject.h"

#include <QMetaType>
#include <QVariant>
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

#include <QList>
#include "chat.h"
#include "geochatmessage.h"
#include "chatlocated.h"
#include "user.h"

class LIBQTELEGRAMSHARED_EXPORT GeochatsLocated : public TelegramTypeObject
{
public:
    enum GeochatsLocatedClassType {
        typeGeochatsLocated = 0x48feb267
    };

    GeochatsLocated(GeochatsLocatedClassType classType = typeGeochatsLocated, InboundPkt *in = 0);
    GeochatsLocated(InboundPkt *in);
    GeochatsLocated(const Null&);
    virtual ~GeochatsLocated();

    void setChats(const QList<Chat> &chats);
    QList<Chat> chats() const;

    void setMessages(const QList<GeoChatMessage> &messages);
    QList<GeoChatMessage> messages() const;

    void setResults(const QList<ChatLocated> &results);
    QList<ChatLocated> results() const;

    void setUsers(const QList<User> &users);
    QList<User> users() const;

    void setClassType(GeochatsLocatedClassType classType);
    GeochatsLocatedClassType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    QMap<QString, QVariant> toMap() const;
    static GeochatsLocated fromMap(const QMap<QString, QVariant> &map);

    bool operator ==(const GeochatsLocated &b) const;

    bool operator==(bool stt) const { return isNull() != stt; }
    bool operator!=(bool stt) const { return !operator ==(stt); }

    QByteArray getHash(QCryptographicHash::Algorithm alg = QCryptographicHash::Md5) const;

private:
    QList<Chat> m_chats;
    QList<GeoChatMessage> m_messages;
    QList<ChatLocated> m_results;
    QList<User> m_users;
    GeochatsLocatedClassType m_classType;
};

Q_DECLARE_METATYPE(GeochatsLocated)

QDataStream LIBQTELEGRAMSHARED_EXPORT &operator<<(QDataStream &stream, const GeochatsLocated &item);
QDataStream LIBQTELEGRAMSHARED_EXPORT &operator>>(QDataStream &stream, GeochatsLocated &item);

inline GeochatsLocated::GeochatsLocated(GeochatsLocatedClassType classType, InboundPkt *in) :
    m_classType(classType)
{
    if(in) fetch(in);
}

inline GeochatsLocated::GeochatsLocated(InboundPkt *in) :
    m_classType(typeGeochatsLocated)
{
    fetch(in);
}

inline GeochatsLocated::GeochatsLocated(const Null &null) :
    TelegramTypeObject(null),
    m_classType(typeGeochatsLocated)
{
}

inline GeochatsLocated::~GeochatsLocated() {
}

inline void GeochatsLocated::setChats(const QList<Chat> &chats) {
    m_chats = chats;
}

inline QList<Chat> GeochatsLocated::chats() const {
    return m_chats;
}

inline void GeochatsLocated::setMessages(const QList<GeoChatMessage> &messages) {
    m_messages = messages;
}

inline QList<GeoChatMessage> GeochatsLocated::messages() const {
    return m_messages;
}

inline void GeochatsLocated::setResults(const QList<ChatLocated> &results) {
    m_results = results;
}

inline QList<ChatLocated> GeochatsLocated::results() const {
    return m_results;
}

inline void GeochatsLocated::setUsers(const QList<User> &users) {
    m_users = users;
}

inline QList<User> GeochatsLocated::users() const {
    return m_users;
}

inline bool GeochatsLocated::operator ==(const GeochatsLocated &b) const {
    return m_classType == b.m_classType &&
           m_chats == b.m_chats &&
           m_messages == b.m_messages &&
           m_results == b.m_results &&
           m_users == b.m_users;
}

inline void GeochatsLocated::setClassType(GeochatsLocated::GeochatsLocatedClassType classType) {
    m_classType = classType;
}

inline GeochatsLocated::GeochatsLocatedClassType GeochatsLocated::classType() const {
    return m_classType;
}

inline bool GeochatsLocated::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeGeochatsLocated: {
        if(in->fetchInt() != (qint32)CoreTypes::typeVector) return false;
        qint32 m_results_length = in->fetchInt();
        m_results.clear();
        for (qint32 i = 0; i < m_results_length; i++) {
            ChatLocated type;
            type.fetch(in);
            m_results.append(type);
        }
        if(in->fetchInt() != (qint32)CoreTypes::typeVector) return false;
        qint32 m_messages_length = in->fetchInt();
        m_messages.clear();
        for (qint32 i = 0; i < m_messages_length; i++) {
            GeoChatMessage type;
            type.fetch(in);
            m_messages.append(type);
        }
        if(in->fetchInt() != (qint32)CoreTypes::typeVector) return false;
        qint32 m_chats_length = in->fetchInt();
        m_chats.clear();
        for (qint32 i = 0; i < m_chats_length; i++) {
            Chat type;
            type.fetch(in);
            m_chats.append(type);
        }
        if(in->fetchInt() != (qint32)CoreTypes::typeVector) return false;
        qint32 m_users_length = in->fetchInt();
        m_users.clear();
        for (qint32 i = 0; i < m_users_length; i++) {
            User type;
            type.fetch(in);
            m_users.append(type);
        }
        m_classType = static_cast<GeochatsLocatedClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

inline bool GeochatsLocated::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeGeochatsLocated: {
        out->appendInt(CoreTypes::typeVector);
        out->appendInt(m_results.count());
        for (qint32 i = 0; i < m_results.count(); i++) {
            m_results[i].push(out);
        }
        out->appendInt(CoreTypes::typeVector);
        out->appendInt(m_messages.count());
        for (qint32 i = 0; i < m_messages.count(); i++) {
            m_messages[i].push(out);
        }
        out->appendInt(CoreTypes::typeVector);
        out->appendInt(m_chats.count());
        for (qint32 i = 0; i < m_chats.count(); i++) {
            m_chats[i].push(out);
        }
        out->appendInt(CoreTypes::typeVector);
        out->appendInt(m_users.count());
        for (qint32 i = 0; i < m_users.count(); i++) {
            m_users[i].push(out);
        }
        return true;
    }
        break;
    
    default:
        return false;
    }
}

inline QMap<QString, QVariant> GeochatsLocated::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeGeochatsLocated: {
        result["classType"] = "GeochatsLocated::typeGeochatsLocated";
        QList<QVariant> _results;
        Q_FOREACH(const ChatLocated &m__type, m_results)
            _results << m__type.toMap();
        result["results"] = _results;
        QList<QVariant> _messages;
        Q_FOREACH(const GeoChatMessage &m__type, m_messages)
            _messages << m__type.toMap();
        result["messages"] = _messages;
        QList<QVariant> _chats;
        Q_FOREACH(const Chat &m__type, m_chats)
            _chats << m__type.toMap();
        result["chats"] = _chats;
        QList<QVariant> _users;
        Q_FOREACH(const User &m__type, m_users)
            _users << m__type.toMap();
        result["users"] = _users;
        return result;
    }
        break;
    
    default:
        return result;
    }
}

inline GeochatsLocated GeochatsLocated::fromMap(const QMap<QString, QVariant> &map) {
    GeochatsLocated result;
    if(map.value("classType").toString() == "GeochatsLocated::typeGeochatsLocated") {
        result.setClassType(typeGeochatsLocated);
        QList<QVariant> map_results = map["results"].toList();
        QList<ChatLocated> _results;
        Q_FOREACH(const QVariant &var, map_results)
            _results << ChatLocated::fromMap(var.toMap());
        result.setResults(_results);
        QList<QVariant> map_messages = map["messages"].toList();
        QList<GeoChatMessage> _messages;
        Q_FOREACH(const QVariant &var, map_messages)
            _messages << GeoChatMessage::fromMap(var.toMap());
        result.setMessages(_messages);
        QList<QVariant> map_chats = map["chats"].toList();
        QList<Chat> _chats;
        Q_FOREACH(const QVariant &var, map_chats)
            _chats << Chat::fromMap(var.toMap());
        result.setChats(_chats);
        QList<QVariant> map_users = map["users"].toList();
        QList<User> _users;
        Q_FOREACH(const QVariant &var, map_users)
            _users << User::fromMap(var.toMap());
        result.setUsers(_users);
        return result;
    }
    return result;
}

inline QByteArray GeochatsLocated::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

inline QDataStream &operator<<(QDataStream &stream, const GeochatsLocated &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case GeochatsLocated::typeGeochatsLocated:
        stream << item.results();
        stream << item.messages();
        stream << item.chats();
        stream << item.users();
        break;
    }
    return stream;
}

inline QDataStream &operator>>(QDataStream &stream, GeochatsLocated &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<GeochatsLocated::GeochatsLocatedClassType>(type));
    switch(type) {
    case GeochatsLocated::typeGeochatsLocated: {
        QList<ChatLocated> m_results;
        stream >> m_results;
        item.setResults(m_results);
        QList<GeoChatMessage> m_messages;
        stream >> m_messages;
        item.setMessages(m_messages);
        QList<Chat> m_chats;
        stream >> m_chats;
        item.setChats(m_chats);
        QList<User> m_users;
        stream >> m_users;
        item.setUsers(m_users);
    }
        break;
    }
    return stream;
}


#endif // LQTG_TYPE_GEOCHATSLOCATED
