// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_GEOCHATSSTATEDMESSAGE
#define LQTG_TYPE_GEOCHATSSTATEDMESSAGE

#include "telegramtypeobject.h"

#include <QMetaType>
#include <QVariant>
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>

#include <QList>
#include "chat.h"
#include "geochatmessage.h"
#include <QtGlobal>
#include "user.h"

class LIBQTELEGRAMSHARED_EXPORT GeochatsStatedMessage : public TelegramTypeObject
{
public:
    enum GeochatsStatedMessageClassType {
        typeGeochatsStatedMessage = 0x17b1578b
    };

    GeochatsStatedMessage(GeochatsStatedMessageClassType classType = typeGeochatsStatedMessage, InboundPkt *in = 0);
    GeochatsStatedMessage(InboundPkt *in);
    GeochatsStatedMessage(const Null&);
    virtual ~GeochatsStatedMessage();

    void setChats(const QList<Chat> &chats);
    QList<Chat> chats() const;

    void setMessage(const GeoChatMessage &message);
    GeoChatMessage message() const;

    void setSeq(qint32 seq);
    qint32 seq() const;

    void setUsers(const QList<User> &users);
    QList<User> users() const;

    void setClassType(GeochatsStatedMessageClassType classType);
    GeochatsStatedMessageClassType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    QMap<QString, QVariant> toMap() const;
    static GeochatsStatedMessage fromMap(const QMap<QString, QVariant> &map);

    bool operator ==(const GeochatsStatedMessage &b) const;

    bool operator==(bool stt) const { return isNull() != stt; }
    bool operator!=(bool stt) const { return !operator ==(stt); }

    QByteArray getHash(QCryptographicHash::Algorithm alg = QCryptographicHash::Md5) const;

private:
    QList<Chat> m_chats;
    GeoChatMessage m_message;
    qint32 m_seq;
    QList<User> m_users;
    GeochatsStatedMessageClassType m_classType;
};

Q_DECLARE_METATYPE(GeochatsStatedMessage)

QDataStream LIBQTELEGRAMSHARED_EXPORT &operator<<(QDataStream &stream, const GeochatsStatedMessage &item);
QDataStream LIBQTELEGRAMSHARED_EXPORT &operator>>(QDataStream &stream, GeochatsStatedMessage &item);

inline GeochatsStatedMessage::GeochatsStatedMessage(GeochatsStatedMessageClassType classType, InboundPkt *in) :
    m_seq(0),
    m_classType(classType)
{
    if(in) fetch(in);
}

inline GeochatsStatedMessage::GeochatsStatedMessage(InboundPkt *in) :
    m_seq(0),
    m_classType(typeGeochatsStatedMessage)
{
    fetch(in);
}

inline GeochatsStatedMessage::GeochatsStatedMessage(const Null &null) :
    TelegramTypeObject(null),
    m_seq(0),
    m_classType(typeGeochatsStatedMessage)
{
}

inline GeochatsStatedMessage::~GeochatsStatedMessage() {
}

inline void GeochatsStatedMessage::setChats(const QList<Chat> &chats) {
    m_chats = chats;
}

inline QList<Chat> GeochatsStatedMessage::chats() const {
    return m_chats;
}

inline void GeochatsStatedMessage::setMessage(const GeoChatMessage &message) {
    m_message = message;
}

inline GeoChatMessage GeochatsStatedMessage::message() const {
    return m_message;
}

inline void GeochatsStatedMessage::setSeq(qint32 seq) {
    m_seq = seq;
}

inline qint32 GeochatsStatedMessage::seq() const {
    return m_seq;
}

inline void GeochatsStatedMessage::setUsers(const QList<User> &users) {
    m_users = users;
}

inline QList<User> GeochatsStatedMessage::users() const {
    return m_users;
}

inline bool GeochatsStatedMessage::operator ==(const GeochatsStatedMessage &b) const {
    return m_classType == b.m_classType &&
           m_chats == b.m_chats &&
           m_message == b.m_message &&
           m_seq == b.m_seq &&
           m_users == b.m_users;
}

inline void GeochatsStatedMessage::setClassType(GeochatsStatedMessage::GeochatsStatedMessageClassType classType) {
    m_classType = classType;
}

inline GeochatsStatedMessage::GeochatsStatedMessageClassType GeochatsStatedMessage::classType() const {
    return m_classType;
}

inline bool GeochatsStatedMessage::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeGeochatsStatedMessage: {
        m_message.fetch(in);
        if(in->fetchInt() != (qint32)CoreTypes::typeVector) return false;
        qint32 m_chats_length = in->fetchInt();
        m_chats.clear();
        for (qint32 i = 0; i < m_chats_length; i++) {
            Chat type;
            type.fetch(in);
            m_chats.append(type);
        }
        if(in->fetchInt() != (qint32)CoreTypes::typeVector) return false;
        qint32 m_users_length = in->fetchInt();
        m_users.clear();
        for (qint32 i = 0; i < m_users_length; i++) {
            User type;
            type.fetch(in);
            m_users.append(type);
        }
        m_seq = in->fetchInt();
        m_classType = static_cast<GeochatsStatedMessageClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

inline bool GeochatsStatedMessage::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeGeochatsStatedMessage: {
        m_message.push(out);
        out->appendInt(CoreTypes::typeVector);
        out->appendInt(m_chats.count());
        for (qint32 i = 0; i < m_chats.count(); i++) {
            m_chats[i].push(out);
        }
        out->appendInt(CoreTypes::typeVector);
        out->appendInt(m_users.count());
        for (qint32 i = 0; i < m_users.count(); i++) {
            m_users[i].push(out);
        }
        out->appendInt(m_seq);
        return true;
    }
        break;
    
    default:
        return false;
    }
}

inline QMap<QString, QVariant> GeochatsStatedMessage::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeGeochatsStatedMessage: {
        result["classType"] = "GeochatsStatedMessage::typeGeochatsStatedMessage";
        result["message"] = m_message.toMap();
        QList<QVariant> _chats;
        Q_FOREACH(const Chat &m__type, m_chats)
            _chats << m__type.toMap();
        result["chats"] = _chats;
        QList<QVariant> _users;
        Q_FOREACH(const User &m__type, m_users)
            _users << m__type.toMap();
        result["users"] = _users;
        result["seq"] = QVariant::fromValue<qint32>(seq());
        return result;
    }
        break;
    
    default:
        return result;
    }
}

inline GeochatsStatedMessage GeochatsStatedMessage::fromMap(const QMap<QString, QVariant> &map) {
    GeochatsStatedMessage result;
    if(map.value("classType").toString() == "GeochatsStatedMessage::typeGeochatsStatedMessage") {
        result.setClassType(typeGeochatsStatedMessage);
        result.setMessage( GeoChatMessage::fromMap(map.value("message").toMap()) );
        QList<QVariant> map_chats = map["chats"].toList();
        QList<Chat> _chats;
        Q_FOREACH(const QVariant &var, map_chats)
            _chats << Chat::fromMap(var.toMap());
        result.setChats(_chats);
        QList<QVariant> map_users = map["users"].toList();
        QList<User> _users;
        Q_FOREACH(const QVariant &var, map_users)
            _users << User::fromMap(var.toMap());
        result.setUsers(_users);
        result.setSeq( map.value("seq").value<qint32>() );
        return result;
    }
    return result;
}

inline QByteArray GeochatsStatedMessage::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

inline QDataStream &operator<<(QDataStream &stream, const GeochatsStatedMessage &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case GeochatsStatedMessage::typeGeochatsStatedMessage:
        stream << item.message();
        stream << item.chats();
        stream << item.users();
        stream << item.seq();
        break;
    }
    return stream;
}

inline QDataStream &operator>>(QDataStream &stream, GeochatsStatedMessage &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<GeochatsStatedMessage::GeochatsStatedMessageClassType>(type));
    switch(type) {
    case GeochatsStatedMessage::typeGeochatsStatedMessage: {
        GeoChatMessage m_message;
        stream >> m_message;
        item.setMessage(m_message);
        QList<Chat> m_chats;
        stream >> m_chats;
        item.setChats(m_chats);
        QList<User> m_users;
        stream >> m_users;
        item.setUsers(m_users);
        qint32 m_seq;
        stream >> m_seq;
        item.setSeq(m_seq);
    }
        break;
    }
    return stream;
}


#endif // LQTG_TYPE_GEOCHATSSTATEDMESSAGE
