// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_MESSAGESMESSAGE
#define LQTG_TYPE_MESSAGESMESSAGE

#include "telegramtypeobject.h"

#include <QMetaType>
#include <QVariant>
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>


class LIBQTELEGRAMSHARED_EXPORT MessagesMessage : public TelegramTypeObject
{
public:
    enum MessagesMessageClassType {
        typeMessagesMessageEmpty = 0x3f4e0648
    };

    MessagesMessage(MessagesMessageClassType classType = typeMessagesMessageEmpty, InboundPkt *in = 0);
    MessagesMessage(InboundPkt *in);
    MessagesMessage(const Null&);
    virtual ~MessagesMessage();

    void setClassType(MessagesMessageClassType classType);
    MessagesMessageClassType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    QMap<QString, QVariant> toMap() const;
    static MessagesMessage fromMap(const QMap<QString, QVariant> &map);

    bool operator ==(const MessagesMessage &b) const;

    bool operator==(bool stt) const { return isNull() != stt; }
    bool operator!=(bool stt) const { return !operator ==(stt); }

    QByteArray getHash(QCryptographicHash::Algorithm alg = QCryptographicHash::Md5) const;

private:
    MessagesMessageClassType m_classType;
};

Q_DECLARE_METATYPE(MessagesMessage)

QDataStream LIBQTELEGRAMSHARED_EXPORT &operator<<(QDataStream &stream, const MessagesMessage &item);
QDataStream LIBQTELEGRAMSHARED_EXPORT &operator>>(QDataStream &stream, MessagesMessage &item);

inline MessagesMessage::MessagesMessage(MessagesMessageClassType classType, InboundPkt *in) :
    m_classType(classType)
{
    if(in) fetch(in);
}

inline MessagesMessage::MessagesMessage(InboundPkt *in) :
    m_classType(typeMessagesMessageEmpty)
{
    fetch(in);
}

inline MessagesMessage::MessagesMessage(const Null &null) :
    TelegramTypeObject(null),
    m_classType(typeMessagesMessageEmpty)
{
}

inline MessagesMessage::~MessagesMessage() {
}

inline bool MessagesMessage::operator ==(const MessagesMessage &b) const {
    return m_classType == b.m_classType;
}

inline void MessagesMessage::setClassType(MessagesMessage::MessagesMessageClassType classType) {
    m_classType = classType;
}

inline MessagesMessage::MessagesMessageClassType MessagesMessage::classType() const {
    return m_classType;
}

inline bool MessagesMessage::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeMessagesMessageEmpty: {
        m_classType = static_cast<MessagesMessageClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

inline bool MessagesMessage::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeMessagesMessageEmpty: {
        return true;
    }
        break;
    
    default:
        return false;
    }
}

inline QMap<QString, QVariant> MessagesMessage::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeMessagesMessageEmpty: {
        result["classType"] = "MessagesMessage::typeMessagesMessageEmpty";
        return result;
    }
        break;
    
    default:
        return result;
    }
}

inline MessagesMessage MessagesMessage::fromMap(const QMap<QString, QVariant> &map) {
    MessagesMessage result;
    if(map.value("classType").toString() == "MessagesMessage::typeMessagesMessageEmpty") {
        result.setClassType(typeMessagesMessageEmpty);
        return result;
    }
    return result;
}

inline QByteArray MessagesMessage::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

inline QDataStream &operator<<(QDataStream &stream, const MessagesMessage &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case MessagesMessage::typeMessagesMessageEmpty:
        
        break;
    }
    return stream;
}

inline QDataStream &operator>>(QDataStream &stream, MessagesMessage &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<MessagesMessage::MessagesMessageClassType>(type));
    switch(type) {
    case MessagesMessage::typeMessagesMessageEmpty: {
        
    }
        break;
    }
    return stream;
}


#endif // LQTG_TYPE_MESSAGESMESSAGE
