// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_TRUE
#define LQTG_TYPE_TRUE

#include "telegramtypeobject.h"

#include <QMetaType>
#include <QVariant>
#include "core/inboundpkt.h"
#include "core/outboundpkt.h"
#include "../coretypes.h"

#include <QDataStream>


class LIBQTELEGRAMSHARED_EXPORT True : public TelegramTypeObject
{
public:
    enum TrueClassType {
        typeTrue = 0x3fedd339
    };

    True(TrueClassType classType = typeTrue, InboundPkt *in = 0);
    True(InboundPkt *in);
    True(const Null&);
    virtual ~True();

    void setClassType(TrueClassType classType);
    TrueClassType classType() const;

    bool fetch(InboundPkt *in);
    bool push(OutboundPkt *out) const;

    QMap<QString, QVariant> toMap() const;
    static True fromMap(const QMap<QString, QVariant> &map);

    bool operator ==(const True &b) const;

    bool operator==(bool stt) const { return isNull() != stt; }
    bool operator!=(bool stt) const { return !operator ==(stt); }

    QByteArray getHash(QCryptographicHash::Algorithm alg = QCryptographicHash::Md5) const;

private:
    TrueClassType m_classType;
};

Q_DECLARE_METATYPE(True)

QDataStream LIBQTELEGRAMSHARED_EXPORT &operator<<(QDataStream &stream, const True &item);
QDataStream LIBQTELEGRAMSHARED_EXPORT &operator>>(QDataStream &stream, True &item);

inline True::True(TrueClassType classType, InboundPkt *in) :
    m_classType(classType)
{
    if(in) fetch(in);
}

inline True::True(InboundPkt *in) :
    m_classType(typeTrue)
{
    fetch(in);
}

inline True::True(const Null &null) :
    TelegramTypeObject(null),
    m_classType(typeTrue)
{
}

inline True::~True() {
}

inline bool True::operator ==(const True &b) const {
    return m_classType == b.m_classType;
}

inline void True::setClassType(True::TrueClassType classType) {
    m_classType = classType;
}

inline True::TrueClassType True::classType() const {
    return m_classType;
}

inline bool True::fetch(InboundPkt *in) {
    LQTG_FETCH_LOG;
    int x = in->fetchInt();
    switch(x) {
    case typeTrue: {
        m_classType = static_cast<TrueClassType>(x);
        return true;
    }
        break;
    
    default:
        LQTG_FETCH_ASSERT;
        return false;
    }
}

inline bool True::push(OutboundPkt *out) const {
    out->appendInt(m_classType);
    switch(m_classType) {
    case typeTrue: {
        return true;
    }
        break;
    
    default:
        return false;
    }
}

inline QMap<QString, QVariant> True::toMap() const {
    QMap<QString, QVariant> result;
    switch(static_cast<int>(m_classType)) {
    case typeTrue: {
        result["classType"] = "True::typeTrue";
        return result;
    }
        break;
    
    default:
        return result;
    }
}

inline True True::fromMap(const QMap<QString, QVariant> &map) {
    True result;
    if(map.value("classType").toString() == "True::typeTrue") {
        result.setClassType(typeTrue);
        return result;
    }
    return result;
}

inline QByteArray True::getHash(QCryptographicHash::Algorithm alg) const {
    QByteArray data;
    QDataStream str(&data, QIODevice::WriteOnly);
    str << *this;
    return QCryptographicHash::hash(data, alg);
}

inline QDataStream &operator<<(QDataStream &stream, const True &item) {
    stream << static_cast<uint>(item.classType());
    switch(item.classType()) {
    case True::typeTrue:
        
        break;
    }
    return stream;
}

inline QDataStream &operator>>(QDataStream &stream, True &item) {
    uint type = 0;
    stream >> type;
    item.setClassType(static_cast<True::TrueClassType>(type));
    switch(type) {
    case True::typeTrue: {
        
    }
        break;
    }
    return stream;
}


#endif // LQTG_TYPE_TRUE
