// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_CHATINVITE_OBJECT
#define LQTG_TYPE_CHATINVITE_OBJECT

#include "telegramtypeqobject.h"
#include "telegram/types/chatinvite.h"

#include <QPointer>
#include "chatobject.h"

class LIBQTELEGRAMSHARED_EXPORT ChatInviteObject : public TelegramTypeQObject
{
    Q_OBJECT
    Q_ENUMS(ChatInviteClassType)
    Q_PROPERTY(ChatObject* chat READ chat WRITE setChat NOTIFY chatChanged)
    Q_PROPERTY(QString title READ title WRITE setTitle NOTIFY titleChanged)
    Q_PROPERTY(ChatInvite core READ core WRITE setCore NOTIFY coreChanged)
    Q_PROPERTY(quint32 classType READ classType WRITE setClassType NOTIFY classTypeChanged)

public:
    enum ChatInviteClassType {
        TypeChatInviteAlready,
        TypeChatInvite
    };

    ChatInviteObject(const ChatInvite &core, QObject *parent = 0);
    ChatInviteObject(QObject *parent = 0);
    virtual ~ChatInviteObject();

    void setChat(ChatObject* chat);
    ChatObject* chat() const;

    void setTitle(const QString &title);
    QString title() const;

    void setClassType(quint32 classType);
    quint32 classType() const;

    void setCore(const ChatInvite &core);
    ChatInvite core() const;

    ChatInviteObject &operator =(const ChatInvite &b);
    bool operator ==(const ChatInvite &b) const;

Q_SIGNALS:
    void coreChanged();
    void classTypeChanged();
    void chatChanged();
    void titleChanged();

private Q_SLOTS:
    void coreChatChanged();

private:
    QPointer<ChatObject> m_chat;
    ChatInvite m_core;
};

inline ChatInviteObject::ChatInviteObject(const ChatInvite &core, QObject *parent) :
    TelegramTypeQObject(parent),
    m_chat(0),
    m_core(core)
{
    m_chat = new ChatObject(m_core.chat(), this);
    connect(m_chat.data(), &ChatObject::coreChanged, this, &ChatInviteObject::coreChatChanged);
}

inline ChatInviteObject::ChatInviteObject(QObject *parent) :
    TelegramTypeQObject(parent),
    m_chat(0),
    m_core()
{
    m_chat = new ChatObject(m_core.chat(), this);
    connect(m_chat.data(), &ChatObject::coreChanged, this, &ChatInviteObject::coreChatChanged);
}

inline ChatInviteObject::~ChatInviteObject() {
}

inline void ChatInviteObject::setChat(ChatObject* chat) {
    if(m_chat == chat) return;
    if(m_chat) delete m_chat;
    m_chat = chat;
    if(m_chat) {
        m_chat->setParent(this);
        m_core.setChat(m_chat->core());
        connect(m_chat.data(), &ChatObject::coreChanged, this, &ChatInviteObject::coreChatChanged);
    }
    Q_EMIT chatChanged();
    Q_EMIT coreChanged();
}

inline ChatObject*  ChatInviteObject::chat() const {
    return m_chat;
}

inline void ChatInviteObject::setTitle(const QString &title) {
    if(m_core.title() == title) return;
    m_core.setTitle(title);
    Q_EMIT titleChanged();
    Q_EMIT coreChanged();
}

inline QString ChatInviteObject::title() const {
    return m_core.title();
}

inline ChatInviteObject &ChatInviteObject::operator =(const ChatInvite &b) {
    if(m_core == b) return *this;
    m_core = b;
    m_chat->setCore(b.chat());

    Q_EMIT chatChanged();
    Q_EMIT titleChanged();
    Q_EMIT coreChanged();
    return *this;
}

inline bool ChatInviteObject::operator ==(const ChatInvite &b) const {
    return m_core == b;
}

inline void ChatInviteObject::setClassType(quint32 classType) {
    ChatInvite::ChatInviteClassType result;
    switch(classType) {
    case TypeChatInviteAlready:
        result = ChatInvite::typeChatInviteAlready;
        break;
    case TypeChatInvite:
        result = ChatInvite::typeChatInvite;
        break;
    default:
        result = ChatInvite::typeChatInviteAlready;
        break;
    }

    if(m_core.classType() == result) return;
    m_core.setClassType(result);
    Q_EMIT classTypeChanged();
    Q_EMIT coreChanged();
}

inline quint32 ChatInviteObject::classType() const {
    int result;
    switch(static_cast<qint64>(m_core.classType())) {
    case ChatInvite::typeChatInviteAlready:
        result = TypeChatInviteAlready;
        break;
    case ChatInvite::typeChatInvite:
        result = TypeChatInvite;
        break;
    default:
        result = TypeChatInviteAlready;
        break;
    }

    return result;
}

inline void ChatInviteObject::setCore(const ChatInvite &core) {
    operator =(core);
}

inline ChatInvite ChatInviteObject::core() const {
    return m_core;
}

inline void ChatInviteObject::coreChatChanged() {
    if(m_core.chat() == m_chat->core()) return;
    m_core.setChat(m_chat->core());
    Q_EMIT chatChanged();
    Q_EMIT coreChanged();
}

#endif // LQTG_TYPE_CHATINVITE_OBJECT
