// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_INPUTMEDIA_OBJECT
#define LQTG_TYPE_INPUTMEDIA_OBJECT

#include "telegramtypeqobject.h"
#include "telegram/types/inputmedia.h"

#include <QPointer>
#include "inputfileobject.h"
#include "inputgeopointobject.h"
#include "inputaudioobject.h"
#include "inputdocumentobject.h"
#include "inputphotoobject.h"
#include "inputvideoobject.h"

class LIBQTELEGRAMSHARED_EXPORT InputMediaObject : public TelegramTypeQObject
{
    Q_OBJECT
    Q_ENUMS(InputMediaClassType)
    Q_PROPERTY(QString address READ address WRITE setAddress NOTIFY addressChanged)
    Q_PROPERTY(QList<DocumentAttribute> attributes READ attributes WRITE setAttributes NOTIFY attributesChanged)
    Q_PROPERTY(QString caption READ caption WRITE setCaption NOTIFY captionChanged)
    Q_PROPERTY(qint32 duration READ duration WRITE setDuration NOTIFY durationChanged)
    Q_PROPERTY(InputFileObject* file READ file WRITE setFile NOTIFY fileChanged)
    Q_PROPERTY(QString firstName READ firstName WRITE setFirstName NOTIFY firstNameChanged)
    Q_PROPERTY(InputGeoPointObject* geoPoint READ geoPoint WRITE setGeoPoint NOTIFY geoPointChanged)
    Q_PROPERTY(qint32 h READ h WRITE setH NOTIFY hChanged)
    Q_PROPERTY(InputAudioObject* idInputAudio READ idInputAudio WRITE setIdInputAudio NOTIFY idInputAudioChanged)
    Q_PROPERTY(InputDocumentObject* idInputDocument READ idInputDocument WRITE setIdInputDocument NOTIFY idInputDocumentChanged)
    Q_PROPERTY(InputPhotoObject* idInputPhoto READ idInputPhoto WRITE setIdInputPhoto NOTIFY idInputPhotoChanged)
    Q_PROPERTY(InputVideoObject* idInputVideo READ idInputVideo WRITE setIdInputVideo NOTIFY idInputVideoChanged)
    Q_PROPERTY(QString lastName READ lastName WRITE setLastName NOTIFY lastNameChanged)
    Q_PROPERTY(QString mimeType READ mimeType WRITE setMimeType NOTIFY mimeTypeChanged)
    Q_PROPERTY(QString phoneNumber READ phoneNumber WRITE setPhoneNumber NOTIFY phoneNumberChanged)
    Q_PROPERTY(QString provider READ provider WRITE setProvider NOTIFY providerChanged)
    Q_PROPERTY(InputFileObject* thumb READ thumb WRITE setThumb NOTIFY thumbChanged)
    Q_PROPERTY(QString title READ title WRITE setTitle NOTIFY titleChanged)
    Q_PROPERTY(QString venueId READ venueId WRITE setVenueId NOTIFY venueIdChanged)
    Q_PROPERTY(qint32 w READ w WRITE setW NOTIFY wChanged)
    Q_PROPERTY(InputMedia core READ core WRITE setCore NOTIFY coreChanged)
    Q_PROPERTY(quint32 classType READ classType WRITE setClassType NOTIFY classTypeChanged)

public:
    enum InputMediaClassType {
        TypeInputMediaEmpty,
        TypeInputMediaUploadedPhoto,
        TypeInputMediaPhoto,
        TypeInputMediaGeoPoint,
        TypeInputMediaContact,
        TypeInputMediaUploadedVideo,
        TypeInputMediaUploadedThumbVideo,
        TypeInputMediaVideo,
        TypeInputMediaUploadedAudio,
        TypeInputMediaAudio,
        TypeInputMediaUploadedDocument,
        TypeInputMediaUploadedThumbDocument,
        TypeInputMediaDocument,
        TypeInputMediaVenue
    };

    InputMediaObject(const InputMedia &core, QObject *parent = 0);
    InputMediaObject(QObject *parent = 0);
    virtual ~InputMediaObject();

    void setAddress(const QString &address);
    QString address() const;

    void setAttributes(const QList<DocumentAttribute> &attributes);
    QList<DocumentAttribute> attributes() const;

    void setCaption(const QString &caption);
    QString caption() const;

    void setDuration(qint32 duration);
    qint32 duration() const;

    void setFile(InputFileObject* file);
    InputFileObject* file() const;

    void setFirstName(const QString &firstName);
    QString firstName() const;

    void setGeoPoint(InputGeoPointObject* geoPoint);
    InputGeoPointObject* geoPoint() const;

    void setH(qint32 h);
    qint32 h() const;

    void setIdInputAudio(InputAudioObject* idInputAudio);
    InputAudioObject* idInputAudio() const;

    void setIdInputDocument(InputDocumentObject* idInputDocument);
    InputDocumentObject* idInputDocument() const;

    void setIdInputPhoto(InputPhotoObject* idInputPhoto);
    InputPhotoObject* idInputPhoto() const;

    void setIdInputVideo(InputVideoObject* idInputVideo);
    InputVideoObject* idInputVideo() const;

    void setLastName(const QString &lastName);
    QString lastName() const;

    void setMimeType(const QString &mimeType);
    QString mimeType() const;

    void setPhoneNumber(const QString &phoneNumber);
    QString phoneNumber() const;

    void setProvider(const QString &provider);
    QString provider() const;

    void setThumb(InputFileObject* thumb);
    InputFileObject* thumb() const;

    void setTitle(const QString &title);
    QString title() const;

    void setVenueId(const QString &venueId);
    QString venueId() const;

    void setW(qint32 w);
    qint32 w() const;

    void setClassType(quint32 classType);
    quint32 classType() const;

    void setCore(const InputMedia &core);
    InputMedia core() const;

    InputMediaObject &operator =(const InputMedia &b);
    bool operator ==(const InputMedia &b) const;

Q_SIGNALS:
    void coreChanged();
    void classTypeChanged();
    void addressChanged();
    void attributesChanged();
    void captionChanged();
    void durationChanged();
    void fileChanged();
    void firstNameChanged();
    void geoPointChanged();
    void hChanged();
    void idInputAudioChanged();
    void idInputDocumentChanged();
    void idInputPhotoChanged();
    void idInputVideoChanged();
    void lastNameChanged();
    void mimeTypeChanged();
    void phoneNumberChanged();
    void providerChanged();
    void thumbChanged();
    void titleChanged();
    void venueIdChanged();
    void wChanged();

private Q_SLOTS:
    void coreFileChanged();
    void coreGeoPointChanged();
    void coreIdInputAudioChanged();
    void coreIdInputDocumentChanged();
    void coreIdInputPhotoChanged();
    void coreIdInputVideoChanged();
    void coreThumbChanged();

private:
    QPointer<InputFileObject> m_file;
    QPointer<InputGeoPointObject> m_geoPoint;
    QPointer<InputAudioObject> m_idInputAudio;
    QPointer<InputDocumentObject> m_idInputDocument;
    QPointer<InputPhotoObject> m_idInputPhoto;
    QPointer<InputVideoObject> m_idInputVideo;
    QPointer<InputFileObject> m_thumb;
    InputMedia m_core;
};

inline InputMediaObject::InputMediaObject(const InputMedia &core, QObject *parent) :
    TelegramTypeQObject(parent),
    m_file(0),
    m_geoPoint(0),
    m_idInputAudio(0),
    m_idInputDocument(0),
    m_idInputPhoto(0),
    m_idInputVideo(0),
    m_thumb(0),
    m_core(core)
{
    m_file = new InputFileObject(m_core.file(), this);
    connect(m_file.data(), &InputFileObject::coreChanged, this, &InputMediaObject::coreFileChanged);
    m_geoPoint = new InputGeoPointObject(m_core.geoPoint(), this);
    connect(m_geoPoint.data(), &InputGeoPointObject::coreChanged, this, &InputMediaObject::coreGeoPointChanged);
    m_idInputAudio = new InputAudioObject(m_core.idInputAudio(), this);
    connect(m_idInputAudio.data(), &InputAudioObject::coreChanged, this, &InputMediaObject::coreIdInputAudioChanged);
    m_idInputDocument = new InputDocumentObject(m_core.idInputDocument(), this);
    connect(m_idInputDocument.data(), &InputDocumentObject::coreChanged, this, &InputMediaObject::coreIdInputDocumentChanged);
    m_idInputPhoto = new InputPhotoObject(m_core.idInputPhoto(), this);
    connect(m_idInputPhoto.data(), &InputPhotoObject::coreChanged, this, &InputMediaObject::coreIdInputPhotoChanged);
    m_idInputVideo = new InputVideoObject(m_core.idInputVideo(), this);
    connect(m_idInputVideo.data(), &InputVideoObject::coreChanged, this, &InputMediaObject::coreIdInputVideoChanged);
    m_thumb = new InputFileObject(m_core.thumb(), this);
    connect(m_thumb.data(), &InputFileObject::coreChanged, this, &InputMediaObject::coreThumbChanged);
}

inline InputMediaObject::InputMediaObject(QObject *parent) :
    TelegramTypeQObject(parent),
    m_file(0),
    m_geoPoint(0),
    m_idInputAudio(0),
    m_idInputDocument(0),
    m_idInputPhoto(0),
    m_idInputVideo(0),
    m_thumb(0),
    m_core()
{
    m_file = new InputFileObject(m_core.file(), this);
    connect(m_file.data(), &InputFileObject::coreChanged, this, &InputMediaObject::coreFileChanged);
    m_geoPoint = new InputGeoPointObject(m_core.geoPoint(), this);
    connect(m_geoPoint.data(), &InputGeoPointObject::coreChanged, this, &InputMediaObject::coreGeoPointChanged);
    m_idInputAudio = new InputAudioObject(m_core.idInputAudio(), this);
    connect(m_idInputAudio.data(), &InputAudioObject::coreChanged, this, &InputMediaObject::coreIdInputAudioChanged);
    m_idInputDocument = new InputDocumentObject(m_core.idInputDocument(), this);
    connect(m_idInputDocument.data(), &InputDocumentObject::coreChanged, this, &InputMediaObject::coreIdInputDocumentChanged);
    m_idInputPhoto = new InputPhotoObject(m_core.idInputPhoto(), this);
    connect(m_idInputPhoto.data(), &InputPhotoObject::coreChanged, this, &InputMediaObject::coreIdInputPhotoChanged);
    m_idInputVideo = new InputVideoObject(m_core.idInputVideo(), this);
    connect(m_idInputVideo.data(), &InputVideoObject::coreChanged, this, &InputMediaObject::coreIdInputVideoChanged);
    m_thumb = new InputFileObject(m_core.thumb(), this);
    connect(m_thumb.data(), &InputFileObject::coreChanged, this, &InputMediaObject::coreThumbChanged);
}

inline InputMediaObject::~InputMediaObject() {
}

inline void InputMediaObject::setAddress(const QString &address) {
    if(m_core.address() == address) return;
    m_core.setAddress(address);
    Q_EMIT addressChanged();
    Q_EMIT coreChanged();
}

inline QString InputMediaObject::address() const {
    return m_core.address();
}

inline void InputMediaObject::setAttributes(const QList<DocumentAttribute> &attributes) {
    if(m_core.attributes() == attributes) return;
    m_core.setAttributes(attributes);
    Q_EMIT attributesChanged();
    Q_EMIT coreChanged();
}

inline QList<DocumentAttribute> InputMediaObject::attributes() const {
    return m_core.attributes();
}

inline void InputMediaObject::setCaption(const QString &caption) {
    if(m_core.caption() == caption) return;
    m_core.setCaption(caption);
    Q_EMIT captionChanged();
    Q_EMIT coreChanged();
}

inline QString InputMediaObject::caption() const {
    return m_core.caption();
}

inline void InputMediaObject::setDuration(qint32 duration) {
    if(m_core.duration() == duration) return;
    m_core.setDuration(duration);
    Q_EMIT durationChanged();
    Q_EMIT coreChanged();
}

inline qint32 InputMediaObject::duration() const {
    return m_core.duration();
}

inline void InputMediaObject::setFile(InputFileObject* file) {
    if(m_file == file) return;
    if(m_file) delete m_file;
    m_file = file;
    if(m_file) {
        m_file->setParent(this);
        m_core.setFile(m_file->core());
        connect(m_file.data(), &InputFileObject::coreChanged, this, &InputMediaObject::coreFileChanged);
    }
    Q_EMIT fileChanged();
    Q_EMIT coreChanged();
}

inline InputFileObject*  InputMediaObject::file() const {
    return m_file;
}

inline void InputMediaObject::setFirstName(const QString &firstName) {
    if(m_core.firstName() == firstName) return;
    m_core.setFirstName(firstName);
    Q_EMIT firstNameChanged();
    Q_EMIT coreChanged();
}

inline QString InputMediaObject::firstName() const {
    return m_core.firstName();
}

inline void InputMediaObject::setGeoPoint(InputGeoPointObject* geoPoint) {
    if(m_geoPoint == geoPoint) return;
    if(m_geoPoint) delete m_geoPoint;
    m_geoPoint = geoPoint;
    if(m_geoPoint) {
        m_geoPoint->setParent(this);
        m_core.setGeoPoint(m_geoPoint->core());
        connect(m_geoPoint.data(), &InputGeoPointObject::coreChanged, this, &InputMediaObject::coreGeoPointChanged);
    }
    Q_EMIT geoPointChanged();
    Q_EMIT coreChanged();
}

inline InputGeoPointObject*  InputMediaObject::geoPoint() const {
    return m_geoPoint;
}

inline void InputMediaObject::setH(qint32 h) {
    if(m_core.h() == h) return;
    m_core.setH(h);
    Q_EMIT hChanged();
    Q_EMIT coreChanged();
}

inline qint32 InputMediaObject::h() const {
    return m_core.h();
}

inline void InputMediaObject::setIdInputAudio(InputAudioObject* idInputAudio) {
    if(m_idInputAudio == idInputAudio) return;
    if(m_idInputAudio) delete m_idInputAudio;
    m_idInputAudio = idInputAudio;
    if(m_idInputAudio) {
        m_idInputAudio->setParent(this);
        m_core.setIdInputAudio(m_idInputAudio->core());
        connect(m_idInputAudio.data(), &InputAudioObject::coreChanged, this, &InputMediaObject::coreIdInputAudioChanged);
    }
    Q_EMIT idInputAudioChanged();
    Q_EMIT coreChanged();
}

inline InputAudioObject*  InputMediaObject::idInputAudio() const {
    return m_idInputAudio;
}

inline void InputMediaObject::setIdInputDocument(InputDocumentObject* idInputDocument) {
    if(m_idInputDocument == idInputDocument) return;
    if(m_idInputDocument) delete m_idInputDocument;
    m_idInputDocument = idInputDocument;
    if(m_idInputDocument) {
        m_idInputDocument->setParent(this);
        m_core.setIdInputDocument(m_idInputDocument->core());
        connect(m_idInputDocument.data(), &InputDocumentObject::coreChanged, this, &InputMediaObject::coreIdInputDocumentChanged);
    }
    Q_EMIT idInputDocumentChanged();
    Q_EMIT coreChanged();
}

inline InputDocumentObject*  InputMediaObject::idInputDocument() const {
    return m_idInputDocument;
}

inline void InputMediaObject::setIdInputPhoto(InputPhotoObject* idInputPhoto) {
    if(m_idInputPhoto == idInputPhoto) return;
    if(m_idInputPhoto) delete m_idInputPhoto;
    m_idInputPhoto = idInputPhoto;
    if(m_idInputPhoto) {
        m_idInputPhoto->setParent(this);
        m_core.setIdInputPhoto(m_idInputPhoto->core());
        connect(m_idInputPhoto.data(), &InputPhotoObject::coreChanged, this, &InputMediaObject::coreIdInputPhotoChanged);
    }
    Q_EMIT idInputPhotoChanged();
    Q_EMIT coreChanged();
}

inline InputPhotoObject*  InputMediaObject::idInputPhoto() const {
    return m_idInputPhoto;
}

inline void InputMediaObject::setIdInputVideo(InputVideoObject* idInputVideo) {
    if(m_idInputVideo == idInputVideo) return;
    if(m_idInputVideo) delete m_idInputVideo;
    m_idInputVideo = idInputVideo;
    if(m_idInputVideo) {
        m_idInputVideo->setParent(this);
        m_core.setIdInputVideo(m_idInputVideo->core());
        connect(m_idInputVideo.data(), &InputVideoObject::coreChanged, this, &InputMediaObject::coreIdInputVideoChanged);
    }
    Q_EMIT idInputVideoChanged();
    Q_EMIT coreChanged();
}

inline InputVideoObject*  InputMediaObject::idInputVideo() const {
    return m_idInputVideo;
}

inline void InputMediaObject::setLastName(const QString &lastName) {
    if(m_core.lastName() == lastName) return;
    m_core.setLastName(lastName);
    Q_EMIT lastNameChanged();
    Q_EMIT coreChanged();
}

inline QString InputMediaObject::lastName() const {
    return m_core.lastName();
}

inline void InputMediaObject::setMimeType(const QString &mimeType) {
    if(m_core.mimeType() == mimeType) return;
    m_core.setMimeType(mimeType);
    Q_EMIT mimeTypeChanged();
    Q_EMIT coreChanged();
}

inline QString InputMediaObject::mimeType() const {
    return m_core.mimeType();
}

inline void InputMediaObject::setPhoneNumber(const QString &phoneNumber) {
    if(m_core.phoneNumber() == phoneNumber) return;
    m_core.setPhoneNumber(phoneNumber);
    Q_EMIT phoneNumberChanged();
    Q_EMIT coreChanged();
}

inline QString InputMediaObject::phoneNumber() const {
    return m_core.phoneNumber();
}

inline void InputMediaObject::setProvider(const QString &provider) {
    if(m_core.provider() == provider) return;
    m_core.setProvider(provider);
    Q_EMIT providerChanged();
    Q_EMIT coreChanged();
}

inline QString InputMediaObject::provider() const {
    return m_core.provider();
}

inline void InputMediaObject::setThumb(InputFileObject* thumb) {
    if(m_thumb == thumb) return;
    if(m_thumb) delete m_thumb;
    m_thumb = thumb;
    if(m_thumb) {
        m_thumb->setParent(this);
        m_core.setThumb(m_thumb->core());
        connect(m_thumb.data(), &InputFileObject::coreChanged, this, &InputMediaObject::coreThumbChanged);
    }
    Q_EMIT thumbChanged();
    Q_EMIT coreChanged();
}

inline InputFileObject*  InputMediaObject::thumb() const {
    return m_thumb;
}

inline void InputMediaObject::setTitle(const QString &title) {
    if(m_core.title() == title) return;
    m_core.setTitle(title);
    Q_EMIT titleChanged();
    Q_EMIT coreChanged();
}

inline QString InputMediaObject::title() const {
    return m_core.title();
}

inline void InputMediaObject::setVenueId(const QString &venueId) {
    if(m_core.venueId() == venueId) return;
    m_core.setVenueId(venueId);
    Q_EMIT venueIdChanged();
    Q_EMIT coreChanged();
}

inline QString InputMediaObject::venueId() const {
    return m_core.venueId();
}

inline void InputMediaObject::setW(qint32 w) {
    if(m_core.w() == w) return;
    m_core.setW(w);
    Q_EMIT wChanged();
    Q_EMIT coreChanged();
}

inline qint32 InputMediaObject::w() const {
    return m_core.w();
}

inline InputMediaObject &InputMediaObject::operator =(const InputMedia &b) {
    if(m_core == b) return *this;
    m_core = b;
    m_file->setCore(b.file());
    m_geoPoint->setCore(b.geoPoint());
    m_idInputAudio->setCore(b.idInputAudio());
    m_idInputDocument->setCore(b.idInputDocument());
    m_idInputPhoto->setCore(b.idInputPhoto());
    m_idInputVideo->setCore(b.idInputVideo());
    m_thumb->setCore(b.thumb());

    Q_EMIT addressChanged();
    Q_EMIT attributesChanged();
    Q_EMIT captionChanged();
    Q_EMIT durationChanged();
    Q_EMIT fileChanged();
    Q_EMIT firstNameChanged();
    Q_EMIT geoPointChanged();
    Q_EMIT hChanged();
    Q_EMIT idInputAudioChanged();
    Q_EMIT idInputDocumentChanged();
    Q_EMIT idInputPhotoChanged();
    Q_EMIT idInputVideoChanged();
    Q_EMIT lastNameChanged();
    Q_EMIT mimeTypeChanged();
    Q_EMIT phoneNumberChanged();
    Q_EMIT providerChanged();
    Q_EMIT thumbChanged();
    Q_EMIT titleChanged();
    Q_EMIT venueIdChanged();
    Q_EMIT wChanged();
    Q_EMIT coreChanged();
    return *this;
}

inline bool InputMediaObject::operator ==(const InputMedia &b) const {
    return m_core == b;
}

inline void InputMediaObject::setClassType(quint32 classType) {
    InputMedia::InputMediaClassType result;
    switch(classType) {
    case TypeInputMediaEmpty:
        result = InputMedia::typeInputMediaEmpty;
        break;
    case TypeInputMediaUploadedPhoto:
        result = InputMedia::typeInputMediaUploadedPhoto;
        break;
    case TypeInputMediaPhoto:
        result = InputMedia::typeInputMediaPhoto;
        break;
    case TypeInputMediaGeoPoint:
        result = InputMedia::typeInputMediaGeoPoint;
        break;
    case TypeInputMediaContact:
        result = InputMedia::typeInputMediaContact;
        break;
    case TypeInputMediaUploadedVideo:
        result = InputMedia::typeInputMediaUploadedVideo;
        break;
    case TypeInputMediaUploadedThumbVideo:
        result = InputMedia::typeInputMediaUploadedThumbVideo;
        break;
    case TypeInputMediaVideo:
        result = InputMedia::typeInputMediaVideo;
        break;
    case TypeInputMediaUploadedAudio:
        result = InputMedia::typeInputMediaUploadedAudio;
        break;
    case TypeInputMediaAudio:
        result = InputMedia::typeInputMediaAudio;
        break;
    case TypeInputMediaUploadedDocument:
        result = InputMedia::typeInputMediaUploadedDocument;
        break;
    case TypeInputMediaUploadedThumbDocument:
        result = InputMedia::typeInputMediaUploadedThumbDocument;
        break;
    case TypeInputMediaDocument:
        result = InputMedia::typeInputMediaDocument;
        break;
    case TypeInputMediaVenue:
        result = InputMedia::typeInputMediaVenue;
        break;
    default:
        result = InputMedia::typeInputMediaEmpty;
        break;
    }

    if(m_core.classType() == result) return;
    m_core.setClassType(result);
    Q_EMIT classTypeChanged();
    Q_EMIT coreChanged();
}

inline quint32 InputMediaObject::classType() const {
    int result;
    switch(static_cast<qint64>(m_core.classType())) {
    case InputMedia::typeInputMediaEmpty:
        result = TypeInputMediaEmpty;
        break;
    case InputMedia::typeInputMediaUploadedPhoto:
        result = TypeInputMediaUploadedPhoto;
        break;
    case InputMedia::typeInputMediaPhoto:
        result = TypeInputMediaPhoto;
        break;
    case InputMedia::typeInputMediaGeoPoint:
        result = TypeInputMediaGeoPoint;
        break;
    case InputMedia::typeInputMediaContact:
        result = TypeInputMediaContact;
        break;
    case InputMedia::typeInputMediaUploadedVideo:
        result = TypeInputMediaUploadedVideo;
        break;
    case InputMedia::typeInputMediaUploadedThumbVideo:
        result = TypeInputMediaUploadedThumbVideo;
        break;
    case InputMedia::typeInputMediaVideo:
        result = TypeInputMediaVideo;
        break;
    case InputMedia::typeInputMediaUploadedAudio:
        result = TypeInputMediaUploadedAudio;
        break;
    case InputMedia::typeInputMediaAudio:
        result = TypeInputMediaAudio;
        break;
    case InputMedia::typeInputMediaUploadedDocument:
        result = TypeInputMediaUploadedDocument;
        break;
    case InputMedia::typeInputMediaUploadedThumbDocument:
        result = TypeInputMediaUploadedThumbDocument;
        break;
    case InputMedia::typeInputMediaDocument:
        result = TypeInputMediaDocument;
        break;
    case InputMedia::typeInputMediaVenue:
        result = TypeInputMediaVenue;
        break;
    default:
        result = TypeInputMediaEmpty;
        break;
    }

    return result;
}

inline void InputMediaObject::setCore(const InputMedia &core) {
    operator =(core);
}

inline InputMedia InputMediaObject::core() const {
    return m_core;
}

inline void InputMediaObject::coreFileChanged() {
    if(m_core.file() == m_file->core()) return;
    m_core.setFile(m_file->core());
    Q_EMIT fileChanged();
    Q_EMIT coreChanged();
}

inline void InputMediaObject::coreGeoPointChanged() {
    if(m_core.geoPoint() == m_geoPoint->core()) return;
    m_core.setGeoPoint(m_geoPoint->core());
    Q_EMIT geoPointChanged();
    Q_EMIT coreChanged();
}

inline void InputMediaObject::coreIdInputAudioChanged() {
    if(m_core.idInputAudio() == m_idInputAudio->core()) return;
    m_core.setIdInputAudio(m_idInputAudio->core());
    Q_EMIT idInputAudioChanged();
    Q_EMIT coreChanged();
}

inline void InputMediaObject::coreIdInputDocumentChanged() {
    if(m_core.idInputDocument() == m_idInputDocument->core()) return;
    m_core.setIdInputDocument(m_idInputDocument->core());
    Q_EMIT idInputDocumentChanged();
    Q_EMIT coreChanged();
}

inline void InputMediaObject::coreIdInputPhotoChanged() {
    if(m_core.idInputPhoto() == m_idInputPhoto->core()) return;
    m_core.setIdInputPhoto(m_idInputPhoto->core());
    Q_EMIT idInputPhotoChanged();
    Q_EMIT coreChanged();
}

inline void InputMediaObject::coreIdInputVideoChanged() {
    if(m_core.idInputVideo() == m_idInputVideo->core()) return;
    m_core.setIdInputVideo(m_idInputVideo->core());
    Q_EMIT idInputVideoChanged();
    Q_EMIT coreChanged();
}

inline void InputMediaObject::coreThumbChanged() {
    if(m_core.thumb() == m_thumb->core()) return;
    m_core.setThumb(m_thumb->core());
    Q_EMIT thumbChanged();
    Q_EMIT coreChanged();
}

#endif // LQTG_TYPE_INPUTMEDIA_OBJECT
