// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_USERFULL_OBJECT
#define LQTG_TYPE_USERFULL_OBJECT

#include "telegramtypeqobject.h"
#include "telegram/types/userfull.h"

#include <QPointer>
#include "contactslinkobject.h"
#include "peernotifysettingsobject.h"
#include "photoobject.h"
#include "userobject.h"

class LIBQTELEGRAMSHARED_EXPORT UserFullObject : public TelegramTypeQObject
{
    Q_OBJECT
    Q_ENUMS(UserFullClassType)
    Q_PROPERTY(bool blocked READ blocked WRITE setBlocked NOTIFY blockedChanged)
    Q_PROPERTY(ContactsLinkObject* link READ link WRITE setLink NOTIFY linkChanged)
    Q_PROPERTY(PeerNotifySettingsObject* notifySettings READ notifySettings WRITE setNotifySettings NOTIFY notifySettingsChanged)
    Q_PROPERTY(PhotoObject* profilePhoto READ profilePhoto WRITE setProfilePhoto NOTIFY profilePhotoChanged)
    Q_PROPERTY(QString realFirstName READ realFirstName WRITE setRealFirstName NOTIFY realFirstNameChanged)
    Q_PROPERTY(QString realLastName READ realLastName WRITE setRealLastName NOTIFY realLastNameChanged)
    Q_PROPERTY(UserObject* user READ user WRITE setUser NOTIFY userChanged)
    Q_PROPERTY(UserFull core READ core WRITE setCore NOTIFY coreChanged)
    Q_PROPERTY(quint32 classType READ classType WRITE setClassType NOTIFY classTypeChanged)

public:
    enum UserFullClassType {
        TypeUserFull
    };

    UserFullObject(const UserFull &core, QObject *parent = 0);
    UserFullObject(QObject *parent = 0);
    virtual ~UserFullObject();

    void setBlocked(bool blocked);
    bool blocked() const;

    void setLink(ContactsLinkObject* link);
    ContactsLinkObject* link() const;

    void setNotifySettings(PeerNotifySettingsObject* notifySettings);
    PeerNotifySettingsObject* notifySettings() const;

    void setProfilePhoto(PhotoObject* profilePhoto);
    PhotoObject* profilePhoto() const;

    void setRealFirstName(const QString &realFirstName);
    QString realFirstName() const;

    void setRealLastName(const QString &realLastName);
    QString realLastName() const;

    void setUser(UserObject* user);
    UserObject* user() const;

    void setClassType(quint32 classType);
    quint32 classType() const;

    void setCore(const UserFull &core);
    UserFull core() const;

    UserFullObject &operator =(const UserFull &b);
    bool operator ==(const UserFull &b) const;

Q_SIGNALS:
    void coreChanged();
    void classTypeChanged();
    void blockedChanged();
    void linkChanged();
    void notifySettingsChanged();
    void profilePhotoChanged();
    void realFirstNameChanged();
    void realLastNameChanged();
    void userChanged();

private Q_SLOTS:
    void coreLinkChanged();
    void coreNotifySettingsChanged();
    void coreProfilePhotoChanged();
    void coreUserChanged();

private:
    QPointer<ContactsLinkObject> m_link;
    QPointer<PeerNotifySettingsObject> m_notifySettings;
    QPointer<PhotoObject> m_profilePhoto;
    QPointer<UserObject> m_user;
    UserFull m_core;
};

inline UserFullObject::UserFullObject(const UserFull &core, QObject *parent) :
    TelegramTypeQObject(parent),
    m_link(0),
    m_notifySettings(0),
    m_profilePhoto(0),
    m_user(0),
    m_core(core)
{
    m_link = new ContactsLinkObject(m_core.link(), this);
    connect(m_link.data(), &ContactsLinkObject::coreChanged, this, &UserFullObject::coreLinkChanged);
    m_notifySettings = new PeerNotifySettingsObject(m_core.notifySettings(), this);
    connect(m_notifySettings.data(), &PeerNotifySettingsObject::coreChanged, this, &UserFullObject::coreNotifySettingsChanged);
    m_profilePhoto = new PhotoObject(m_core.profilePhoto(), this);
    connect(m_profilePhoto.data(), &PhotoObject::coreChanged, this, &UserFullObject::coreProfilePhotoChanged);
    m_user = new UserObject(m_core.user(), this);
    connect(m_user.data(), &UserObject::coreChanged, this, &UserFullObject::coreUserChanged);
}

inline UserFullObject::UserFullObject(QObject *parent) :
    TelegramTypeQObject(parent),
    m_link(0),
    m_notifySettings(0),
    m_profilePhoto(0),
    m_user(0),
    m_core()
{
    m_link = new ContactsLinkObject(m_core.link(), this);
    connect(m_link.data(), &ContactsLinkObject::coreChanged, this, &UserFullObject::coreLinkChanged);
    m_notifySettings = new PeerNotifySettingsObject(m_core.notifySettings(), this);
    connect(m_notifySettings.data(), &PeerNotifySettingsObject::coreChanged, this, &UserFullObject::coreNotifySettingsChanged);
    m_profilePhoto = new PhotoObject(m_core.profilePhoto(), this);
    connect(m_profilePhoto.data(), &PhotoObject::coreChanged, this, &UserFullObject::coreProfilePhotoChanged);
    m_user = new UserObject(m_core.user(), this);
    connect(m_user.data(), &UserObject::coreChanged, this, &UserFullObject::coreUserChanged);
}

inline UserFullObject::~UserFullObject() {
}

inline void UserFullObject::setBlocked(bool blocked) {
    if(m_core.blocked() == blocked) return;
    m_core.setBlocked(blocked);
    Q_EMIT blockedChanged();
    Q_EMIT coreChanged();
}

inline bool UserFullObject::blocked() const {
    return m_core.blocked();
}

inline void UserFullObject::setLink(ContactsLinkObject* link) {
    if(m_link == link) return;
    if(m_link) delete m_link;
    m_link = link;
    if(m_link) {
        m_link->setParent(this);
        m_core.setLink(m_link->core());
        connect(m_link.data(), &ContactsLinkObject::coreChanged, this, &UserFullObject::coreLinkChanged);
    }
    Q_EMIT linkChanged();
    Q_EMIT coreChanged();
}

inline ContactsLinkObject*  UserFullObject::link() const {
    return m_link;
}

inline void UserFullObject::setNotifySettings(PeerNotifySettingsObject* notifySettings) {
    if(m_notifySettings == notifySettings) return;
    if(m_notifySettings) delete m_notifySettings;
    m_notifySettings = notifySettings;
    if(m_notifySettings) {
        m_notifySettings->setParent(this);
        m_core.setNotifySettings(m_notifySettings->core());
        connect(m_notifySettings.data(), &PeerNotifySettingsObject::coreChanged, this, &UserFullObject::coreNotifySettingsChanged);
    }
    Q_EMIT notifySettingsChanged();
    Q_EMIT coreChanged();
}

inline PeerNotifySettingsObject*  UserFullObject::notifySettings() const {
    return m_notifySettings;
}

inline void UserFullObject::setProfilePhoto(PhotoObject* profilePhoto) {
    if(m_profilePhoto == profilePhoto) return;
    if(m_profilePhoto) delete m_profilePhoto;
    m_profilePhoto = profilePhoto;
    if(m_profilePhoto) {
        m_profilePhoto->setParent(this);
        m_core.setProfilePhoto(m_profilePhoto->core());
        connect(m_profilePhoto.data(), &PhotoObject::coreChanged, this, &UserFullObject::coreProfilePhotoChanged);
    }
    Q_EMIT profilePhotoChanged();
    Q_EMIT coreChanged();
}

inline PhotoObject*  UserFullObject::profilePhoto() const {
    return m_profilePhoto;
}

inline void UserFullObject::setRealFirstName(const QString &realFirstName) {
    if(m_core.realFirstName() == realFirstName) return;
    m_core.setRealFirstName(realFirstName);
    Q_EMIT realFirstNameChanged();
    Q_EMIT coreChanged();
}

inline QString UserFullObject::realFirstName() const {
    return m_core.realFirstName();
}

inline void UserFullObject::setRealLastName(const QString &realLastName) {
    if(m_core.realLastName() == realLastName) return;
    m_core.setRealLastName(realLastName);
    Q_EMIT realLastNameChanged();
    Q_EMIT coreChanged();
}

inline QString UserFullObject::realLastName() const {
    return m_core.realLastName();
}

inline void UserFullObject::setUser(UserObject* user) {
    if(m_user == user) return;
    if(m_user) delete m_user;
    m_user = user;
    if(m_user) {
        m_user->setParent(this);
        m_core.setUser(m_user->core());
        connect(m_user.data(), &UserObject::coreChanged, this, &UserFullObject::coreUserChanged);
    }
    Q_EMIT userChanged();
    Q_EMIT coreChanged();
}

inline UserObject*  UserFullObject::user() const {
    return m_user;
}

inline UserFullObject &UserFullObject::operator =(const UserFull &b) {
    if(m_core == b) return *this;
    m_core = b;
    m_link->setCore(b.link());
    m_notifySettings->setCore(b.notifySettings());
    m_profilePhoto->setCore(b.profilePhoto());
    m_user->setCore(b.user());

    Q_EMIT blockedChanged();
    Q_EMIT linkChanged();
    Q_EMIT notifySettingsChanged();
    Q_EMIT profilePhotoChanged();
    Q_EMIT realFirstNameChanged();
    Q_EMIT realLastNameChanged();
    Q_EMIT userChanged();
    Q_EMIT coreChanged();
    return *this;
}

inline bool UserFullObject::operator ==(const UserFull &b) const {
    return m_core == b;
}

inline void UserFullObject::setClassType(quint32 classType) {
    UserFull::UserFullClassType result;
    switch(classType) {
    case TypeUserFull:
        result = UserFull::typeUserFull;
        break;
    default:
        result = UserFull::typeUserFull;
        break;
    }

    if(m_core.classType() == result) return;
    m_core.setClassType(result);
    Q_EMIT classTypeChanged();
    Q_EMIT coreChanged();
}

inline quint32 UserFullObject::classType() const {
    int result;
    switch(static_cast<qint64>(m_core.classType())) {
    case UserFull::typeUserFull:
        result = TypeUserFull;
        break;
    default:
        result = TypeUserFull;
        break;
    }

    return result;
}

inline void UserFullObject::setCore(const UserFull &core) {
    operator =(core);
}

inline UserFull UserFullObject::core() const {
    return m_core;
}

inline void UserFullObject::coreLinkChanged() {
    if(m_core.link() == m_link->core()) return;
    m_core.setLink(m_link->core());
    Q_EMIT linkChanged();
    Q_EMIT coreChanged();
}

inline void UserFullObject::coreNotifySettingsChanged() {
    if(m_core.notifySettings() == m_notifySettings->core()) return;
    m_core.setNotifySettings(m_notifySettings->core());
    Q_EMIT notifySettingsChanged();
    Q_EMIT coreChanged();
}

inline void UserFullObject::coreProfilePhotoChanged() {
    if(m_core.profilePhoto() == m_profilePhoto->core()) return;
    m_core.setProfilePhoto(m_profilePhoto->core());
    Q_EMIT profilePhotoChanged();
    Q_EMIT coreChanged();
}

inline void UserFullObject::coreUserChanged() {
    if(m_core.user() == m_user->core()) return;
    m_core.setUser(m_user->core());
    Q_EMIT userChanged();
    Q_EMIT coreChanged();
}

#endif // LQTG_TYPE_USERFULL_OBJECT
