// This file generated by libqtelegram-code-generator.
// You can download it from: https://github.com/Aseman-Land/libqtelegram-code-generator
// DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

#ifndef LQTG_TYPE_USER_OBJECT
#define LQTG_TYPE_USER_OBJECT

#include "telegramtypeqobject.h"
#include "telegram/types/user.h"

#include <QPointer>
#include "userprofilephotoobject.h"
#include "userstatusobject.h"

class LIBQTELEGRAMSHARED_EXPORT UserObject : public TelegramTypeQObject
{
    Q_OBJECT
    Q_ENUMS(UserClassType)
    Q_PROPERTY(qint64 accessHash READ accessHash WRITE setAccessHash NOTIFY accessHashChanged)
    Q_PROPERTY(qint32 botInfoVersion READ botInfoVersion WRITE setBotInfoVersion NOTIFY botInfoVersionChanged)
    Q_PROPERTY(QString firstName READ firstName WRITE setFirstName NOTIFY firstNameChanged)
    Q_PROPERTY(qint32 flags READ flags WRITE setFlags NOTIFY flagsChanged)
    Q_PROPERTY(qint32 id READ id WRITE setId NOTIFY idChanged)
    Q_PROPERTY(QString lastName READ lastName WRITE setLastName NOTIFY lastNameChanged)
    Q_PROPERTY(QString phone READ phone WRITE setPhone NOTIFY phoneChanged)
    Q_PROPERTY(UserProfilePhotoObject* photo READ photo WRITE setPhoto NOTIFY photoChanged)
    Q_PROPERTY(UserStatusObject* status READ status WRITE setStatus NOTIFY statusChanged)
    Q_PROPERTY(QString username READ username WRITE setUsername NOTIFY usernameChanged)
    Q_PROPERTY(User core READ core WRITE setCore NOTIFY coreChanged)
    Q_PROPERTY(quint32 classType READ classType WRITE setClassType NOTIFY classTypeChanged)

public:
    enum UserClassType {
        TypeUserEmpty,
        TypeUser
    };

    UserObject(const User &core, QObject *parent = 0);
    UserObject(QObject *parent = 0);
    virtual ~UserObject();

    void setAccessHash(qint64 accessHash);
    qint64 accessHash() const;

    void setBotInfoVersion(qint32 botInfoVersion);
    qint32 botInfoVersion() const;

    void setFirstName(const QString &firstName);
    QString firstName() const;

    void setFlags(qint32 flags);
    qint32 flags() const;

    void setId(qint32 id);
    qint32 id() const;

    void setLastName(const QString &lastName);
    QString lastName() const;

    void setPhone(const QString &phone);
    QString phone() const;

    void setPhoto(UserProfilePhotoObject* photo);
    UserProfilePhotoObject* photo() const;

    void setStatus(UserStatusObject* status);
    UserStatusObject* status() const;

    void setUsername(const QString &username);
    QString username() const;

    void setClassType(quint32 classType);
    quint32 classType() const;

    void setCore(const User &core);
    User core() const;

    UserObject &operator =(const User &b);
    bool operator ==(const User &b) const;

Q_SIGNALS:
    void coreChanged();
    void classTypeChanged();
    void accessHashChanged();
    void botInfoVersionChanged();
    void firstNameChanged();
    void flagsChanged();
    void idChanged();
    void lastNameChanged();
    void phoneChanged();
    void photoChanged();
    void statusChanged();
    void usernameChanged();

private Q_SLOTS:
    void corePhotoChanged();
    void coreStatusChanged();

private:
    QPointer<UserProfilePhotoObject> m_photo;
    QPointer<UserStatusObject> m_status;
    User m_core;
};

inline UserObject::UserObject(const User &core, QObject *parent) :
    TelegramTypeQObject(parent),
    m_photo(0),
    m_status(0),
    m_core(core)
{
    m_photo = new UserProfilePhotoObject(m_core.photo(), this);
    connect(m_photo.data(), &UserProfilePhotoObject::coreChanged, this, &UserObject::corePhotoChanged);
    m_status = new UserStatusObject(m_core.status(), this);
    connect(m_status.data(), &UserStatusObject::coreChanged, this, &UserObject::coreStatusChanged);
}

inline UserObject::UserObject(QObject *parent) :
    TelegramTypeQObject(parent),
    m_photo(0),
    m_status(0),
    m_core()
{
    m_photo = new UserProfilePhotoObject(m_core.photo(), this);
    connect(m_photo.data(), &UserProfilePhotoObject::coreChanged, this, &UserObject::corePhotoChanged);
    m_status = new UserStatusObject(m_core.status(), this);
    connect(m_status.data(), &UserStatusObject::coreChanged, this, &UserObject::coreStatusChanged);
}

inline UserObject::~UserObject() {
}

inline void UserObject::setAccessHash(qint64 accessHash) {
    if(m_core.accessHash() == accessHash) return;
    m_core.setAccessHash(accessHash);
    Q_EMIT accessHashChanged();
    Q_EMIT coreChanged();
}

inline qint64 UserObject::accessHash() const {
    return m_core.accessHash();
}

inline void UserObject::setBotInfoVersion(qint32 botInfoVersion) {
    if(m_core.botInfoVersion() == botInfoVersion) return;
    m_core.setBotInfoVersion(botInfoVersion);
    Q_EMIT botInfoVersionChanged();
    Q_EMIT coreChanged();
}

inline qint32 UserObject::botInfoVersion() const {
    return m_core.botInfoVersion();
}

inline void UserObject::setFirstName(const QString &firstName) {
    if(m_core.firstName() == firstName) return;
    m_core.setFirstName(firstName);
    Q_EMIT firstNameChanged();
    Q_EMIT coreChanged();
}

inline QString UserObject::firstName() const {
    return m_core.firstName();
}

inline void UserObject::setFlags(qint32 flags) {
    if(m_core.flags() == flags) return;
    m_core.setFlags(flags);
    Q_EMIT flagsChanged();
    Q_EMIT coreChanged();
}

inline qint32 UserObject::flags() const {
    return m_core.flags();
}

inline void UserObject::setId(qint32 id) {
    if(m_core.id() == id) return;
    m_core.setId(id);
    Q_EMIT idChanged();
    Q_EMIT coreChanged();
}

inline qint32 UserObject::id() const {
    return m_core.id();
}

inline void UserObject::setLastName(const QString &lastName) {
    if(m_core.lastName() == lastName) return;
    m_core.setLastName(lastName);
    Q_EMIT lastNameChanged();
    Q_EMIT coreChanged();
}

inline QString UserObject::lastName() const {
    return m_core.lastName();
}

inline void UserObject::setPhone(const QString &phone) {
    if(m_core.phone() == phone) return;
    m_core.setPhone(phone);
    Q_EMIT phoneChanged();
    Q_EMIT coreChanged();
}

inline QString UserObject::phone() const {
    return m_core.phone();
}

inline void UserObject::setPhoto(UserProfilePhotoObject* photo) {
    if(m_photo == photo) return;
    if(m_photo) delete m_photo;
    m_photo = photo;
    if(m_photo) {
        m_photo->setParent(this);
        m_core.setPhoto(m_photo->core());
        connect(m_photo.data(), &UserProfilePhotoObject::coreChanged, this, &UserObject::corePhotoChanged);
    }
    Q_EMIT photoChanged();
    Q_EMIT coreChanged();
}

inline UserProfilePhotoObject*  UserObject::photo() const {
    return m_photo;
}

inline void UserObject::setStatus(UserStatusObject* status) {
    if(m_status == status) return;
    if(m_status) delete m_status;
    m_status = status;
    if(m_status) {
        m_status->setParent(this);
        m_core.setStatus(m_status->core());
        connect(m_status.data(), &UserStatusObject::coreChanged, this, &UserObject::coreStatusChanged);
    }
    Q_EMIT statusChanged();
    Q_EMIT coreChanged();
}

inline UserStatusObject*  UserObject::status() const {
    return m_status;
}

inline void UserObject::setUsername(const QString &username) {
    if(m_core.username() == username) return;
    m_core.setUsername(username);
    Q_EMIT usernameChanged();
    Q_EMIT coreChanged();
}

inline QString UserObject::username() const {
    return m_core.username();
}

inline UserObject &UserObject::operator =(const User &b) {
    if(m_core == b) return *this;
    m_core = b;
    m_photo->setCore(b.photo());
    m_status->setCore(b.status());

    Q_EMIT accessHashChanged();
    Q_EMIT botInfoVersionChanged();
    Q_EMIT firstNameChanged();
    Q_EMIT flagsChanged();
    Q_EMIT idChanged();
    Q_EMIT lastNameChanged();
    Q_EMIT phoneChanged();
    Q_EMIT photoChanged();
    Q_EMIT statusChanged();
    Q_EMIT usernameChanged();
    Q_EMIT coreChanged();
    return *this;
}

inline bool UserObject::operator ==(const User &b) const {
    return m_core == b;
}

inline void UserObject::setClassType(quint32 classType) {
    User::UserClassType result;
    switch(classType) {
    case TypeUserEmpty:
        result = User::typeUserEmpty;
        break;
    case TypeUser:
        result = User::typeUser;
        break;
    default:
        result = User::typeUserEmpty;
        break;
    }

    if(m_core.classType() == result) return;
    m_core.setClassType(result);
    Q_EMIT classTypeChanged();
    Q_EMIT coreChanged();
}

inline quint32 UserObject::classType() const {
    int result;
    switch(static_cast<qint64>(m_core.classType())) {
    case User::typeUserEmpty:
        result = TypeUserEmpty;
        break;
    case User::typeUser:
        result = TypeUser;
        break;
    default:
        result = TypeUserEmpty;
        break;
    }

    return result;
}

inline void UserObject::setCore(const User &core) {
    operator =(core);
}

inline User UserObject::core() const {
    return m_core;
}

inline void UserObject::corePhotoChanged() {
    if(m_core.photo() == m_photo->core()) return;
    m_core.setPhoto(m_photo->core());
    Q_EMIT photoChanged();
    Q_EMIT coreChanged();
}

inline void UserObject::coreStatusChanged() {
    if(m_core.status() == m_status->core()) return;
    m_core.setStatus(m_status->core());
    Q_EMIT statusChanged();
    Q_EMIT coreChanged();
}

#endif // LQTG_TYPE_USER_OBJECT
